### ISSUE TITLE
Infografía Desarrollo de un Software

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/infografia-Band-hi#2]
[Desarrollo de un Software - Gandhi Salazar Cruz.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Band-hi/files/7122617/Desarrollo.de.un.Software.-.Gandhi.Salazar.Cruz.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo. Calificación 21/21.
Evaluó: Fernando Miguel López.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
